861631: Need to prepare documentation for custom toolbar root elementwith Css class.
syncfusion-content/ej2-richtexteditor-docs pull request #54
Opened 2023-12-13 11:19 UTC by venkateshsf3956

861631: Need to prepare documentation for custom toolbar root elementwith Css class.

2023-12-13 11:20 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [861631-rte-cssClass](https://jenkins.syncfusion.com/job/Content/job/ej2-richtexteditor-docs/83/)<br/>**

2023-12-13 12:56 UTC, thangavele commented on ej2-javascript/rich-text-editor/toolbar.md
> +>Note:On opening the dependencies component in the custom toolbar, the Rich Text Editor gets focused out, and a blur handler has been called. During that time range, can't get properly. So, use the c
Remove the Note word. > symbol alone enough

The focus will be lost while rendering the required component for the custom toolbar, causing it to render outside of the Rich Text Editor and triggering a blur event. During that time, proper functionality will not be achievable. Therefore, it is recommended to set the cssClass property or class as `e-rte-elements` in the dependency component.

2023-12-13 13:01 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [861631-rte-cssClass](https://jenkins.syncfusion.com/job/Content/job/ej2-richtexteditor-docs/84/console)**

2023-12-13 13:02 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [861631-rte-cssClass](https://jenkins.syncfusion.com/job/Content/job/ej2-richtexteditor-docs/84/console)**

2023-12-13 13:07 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [861631-rte-cssClass](https://jenkins.syncfusion.com/job/Content/job/ej2-richtexteditor-docs/84/)<br/>**

2023-12-13 13:27 UTC, thangavele commented on ej2-javascript/rich-text-editor/toolbar.md
> +>The focus will be lost while rendering the required component for the custom toolbar, causing it to render outside of the Rich Text Editor and triggering a blur event. During that time, proper funct
give space after >

2023-12-13 13:34 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [861631-rte-cssClass](https://jenkins.syncfusion.com/job/Content/job/ej2-richtexteditor-docs/85/console)**

2023-12-13 13:39 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [861631-rte-cssClass](https://jenkins.syncfusion.com/job/Content/job/ej2-richtexteditor-docs/85/console)**

2023-12-13 13:40 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [861631-rte-cssClass](https://jenkins.syncfusion.com/job/Content/job/ej2-richtexteditor-docs/85/)<br/>**

2023-12-14 06:51 UTC, M-A32 requested changes

2023-12-14 06:51 UTC, M-A32 commented on ej2-javascript/rich-text-editor/toolbar.md
> +> The focus will be lost while rendering the required component for the custom toolbar, causing it to render outside of the Rich Text Editor and triggering a blur event. During that time, proper func
> The focus will be lost while rendering the required component for the custom toolbar, causing it to render outside the Rich Text Editor and triggering a blur event. During that time, proper functionality will not be achievable. Therefore, it is recommended to set the cssClass property or class as `e-rte-elements` in the dependency component.

2023-12-15 03:38 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [861631-rte-cssClass](https://jenkins.syncfusion.com/job/Content/job/ej2-richtexteditor-docs/86/console)**

2023-12-15 03:48 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [861631-rte-cssClass](https://jenkins.syncfusion.com/job/Content/job/ej2-richtexteditor-docs/86/console)**

2023-12-15 03:49 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [861631-rte-cssClass](https://jenkins.syncfusion.com/job/Content/job/ej2-richtexteditor-docs/86/)<br/>**

2023-12-15 05:12 UTC, thangavele approved these changes

2023-12-15 05:12 UTC, merged